### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TheUslessVay** [nmcain/rms-display#1]
I clicked something and ram ranch started playing

**Comment by nmcain** [comment]
Closed as irrelevant

**Comment by TheUslessVay** [comment]
![my turn](https://user-images.githubusercontent.com/34291459/48572853-7a1e3e00-e8bf-11e8-9347-39650868e266.png)

**Comment by TheUslessVay** [comment]
hand it over

**Comment by nmcain** [comment]
kurwa
